import { AlertTriangle, CheckCircle2, Activity, Download, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ResultsCardProps {
  result: {
    risk: "high" | "low" | "moderate" | null;
    confidence: number;
    timestamp: string;
    heatmap?: string;
    notes?: string;
    dicom_metadata?: {
      patient_name?: string;
      study_date?: string;
      modality?: string;
      institution?: string;
    };
  } | null;
}

const ResultsCard = ({ result }: ResultsCardProps) => {
  const generatePDF = async () => {
    if (!result) return;

    const doc = new jsPDF();

    // Header
    doc.setFillColor(41, 128, 185);
    doc.rect(0, 0, 210, 40, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("TB Screening Report", 20, 25);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);

    // Report Info
    doc.text(`Report ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}`, 20, 55);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 62);
    doc.text(`Time: ${result.timestamp}`, 20, 69);

    // DICOM metadata if available
    let yPos = 69;
    if (result.dicom_metadata) {
      yPos += 10;
      doc.setFontSize(14);
      doc.text("DICOM Information", 20, yPos);
      doc.setFontSize(11);
      yPos += 8;
      if (result.dicom_metadata.modality) {
        doc.text(`Modality: ${result.dicom_metadata.modality}`, 20, yPos);
        yPos += 7;
      }
      if (result.dicom_metadata.institution) {
        doc.text(`Institution: ${result.dicom_metadata.institution}`, 20, yPos);
        yPos += 7;
      }
      if (result.dicom_metadata.study_date) {
        doc.text(`Study Date: ${result.dicom_metadata.study_date}`, 20, yPos);
        yPos += 7;
      }
    }

    // Results
    yPos += 8;
    doc.setFontSize(16);
    doc.text("Analysis Results", 20, yPos);
    yPos += 10;

    doc.setFontSize(12);
    doc.text(`Risk Assessment: ${result.risk?.toUpperCase()} RISK`, 20, yPos);
    yPos += 7;
    doc.text(`Confidence Score: ${result.confidence}%`, 20, yPos);
    yPos += 10;

    // Clinical Notes
    if (result.notes) {
      doc.text("Clinical Findings:", 20, yPos);
      yPos += 7;
      doc.setFontSize(10);
      const splitNotes = doc.splitTextToSize(result.notes, 170);
      doc.text(splitNotes, 20, yPos);
      yPos += splitNotes.length * 5 + 10;
      doc.setFontSize(12);
    }

    // Heatmap Image
    if (result.heatmap) {
      doc.text("AI Explanation (Heatmap Analysis):", 20, yPos);
      try {
        doc.addImage(`data:image/png;base64,${result.heatmap}`, "PNG", 20, yPos + 5, 100, 100);
        yPos += 110;
      } catch (e) {
        console.error("Error adding image to PDF", e);
      }
    }

    // Try to add doctor's digital signature
    try {
      const storedUser = localStorage.getItem("user");
      if (storedUser) {
        const user = JSON.parse(storedUser);
        if (user.email) {
          const sigResponse = await fetch(`http://localhost:5000/api/auth/signature/${user.email}`);
          const sigData = await sigResponse.json();
          if (sigData.success && sigData.signature) {
            const sigY = 240;
            doc.setDrawColor(150, 150, 150);
            doc.line(20, sigY, 100, sigY);
            try {
              doc.addImage(sigData.signature, "PNG", 30, sigY - 22, 50, 20);
            } catch (e) {
              console.error("Error adding signature to PDF", e);
            }
            doc.setFontSize(10);
            doc.setTextColor(60, 60, 60);
            doc.text(`Digitally Signed by Dr. ${sigData.username || user.name}`, 20, sigY + 6);
            doc.text(`Date: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 20, sigY + 12);
          }
        }
      }
    } catch (e) {
      console.error("Error fetching signature for PDF", e);
    }

    // Disclaimer
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Disclaimer: This report is generated by an AI Screening System.", 20, 280);
    doc.text("It is not a final medical diagnosis. Please consult a specialist.", 20, 285);

    doc.save("tb-screening-report.pdf");
  };

  if (!result) {
    return (
      <div className="glass-strong rounded-2xl p-6">
        <h3 className="text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
          <Activity className="w-5 h-5 text-primary" />
          Analysis Results
        </h3>
        <div className="flex flex-col items-center justify-center py-10 text-center">
          <div className="w-16 h-16 rounded-full bg-muted flex items-center justify-center mb-4">
            <Activity className="w-8 h-8 text-muted-foreground" />
          </div>
          <p className="text-muted-foreground">Upload an X-ray image to see results</p>
        </div>
      </div>
    );
  }

  const isHighRisk = result.risk === "high";
  const isModerateRisk = result.risk === "moderate";

  let statusColor = "text-success";
  let statusBg = "bg-success/10 border-success/20";
  let statusIcon = <CheckCircle2 className="w-8 h-8 text-success" />;
  let statusText = "Low Risk";
  let progressBarColor = "bg-success";

  if (isHighRisk) {
    statusColor = "text-destructive";
    statusBg = "bg-destructive/10 border-destructive/20";
    statusIcon = <AlertTriangle className="w-8 h-8 text-destructive" />;
    statusText = "High Risk";
    progressBarColor = "bg-destructive";
  } else if (isModerateRisk) {
    statusColor = "text-warning";
    statusBg = "bg-warning/10 border-warning/20";
    statusIcon = <AlertTriangle className="w-8 h-8 text-warning" />;
    statusText = "Moderate Risk";
    progressBarColor = "bg-warning";
  }

  return (
    <div className="glass-strong rounded-2xl p-6 animate-slide-up">
      <h3 className="text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
        <Activity className="w-5 h-5 text-primary" />
        Analysis Results
      </h3>

      <div className={`rounded-xl p-6 border ${statusBg}`}>
        <div className="flex items-center gap-3 mb-4">
          {statusIcon}
          <div>
            <p className={`text-2xl font-bold ${statusColor}`}>
              {statusText}
            </p>
            <p className="text-sm text-muted-foreground">TB Detection Result</p>
          </div>
        </div>

        {/* DICOM Metadata Badge */}
        {result.dicom_metadata && (
          <div className="mb-4 p-3 bg-accent/5 rounded-lg border border-accent/20">
            <p className="text-xs font-semibold text-accent mb-1 flex items-center gap-1">
              📋 DICOM Source Data
            </p>
            <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-xs text-muted-foreground">
              {result.dicom_metadata.modality && <p>Modality: <span className="text-foreground">{result.dicom_metadata.modality}</span></p>}
              {result.dicom_metadata.study_date && <p>Study: <span className="text-foreground">{result.dicom_metadata.study_date}</span></p>}
              {result.dicom_metadata.institution && <p>Institution: <span className="text-foreground">{result.dicom_metadata.institution}</span></p>}
            </div>
          </div>
        )}

        {/* Heatmap Visualization */}
        {result.heatmap && (
          <div className="mb-6">
            <p className="text-sm font-medium text-foreground mb-2 flex items-center gap-2">
              <Activity className="w-4 h-4 text-primary" />
              AI Heatmap Analysis
            </p>
            <div className="relative rounded-lg overflow-hidden border border-border/50 aspect-video bg-black/5">
              <img
                src={`data:image/png;base64,${result.heatmap}`}
                alt="AI Heatmap"
                className="w-full h-full object-contain"
              />
            </div>
            <p className="text-xs text-muted-foreground mt-1">
              Red areas indicate high feature activation (suspicious regions).
            </p>
          </div>
        )}

        {/* Clinical Notes Display */}
        {result.notes && (
          <div className="mb-6 p-4 bg-muted/30 rounded-lg border border-border/50">
            <p className="text-sm font-medium text-foreground mb-2 flex items-center gap-2">
              <FileText className="w-4 h-4 text-primary" />
              Clinical Findings
            </p>
            <p className="text-sm text-foreground/80 italic leading-relaxed">
              "{result.notes}"
            </p>
          </div>
        )}

        {/* Confidence bar */}
        <div className="space-y-2">
          <div className="flex justify-between text-sm">
            <span className="text-muted-foreground">Confidence Score</span>
            <span className="font-semibold text-foreground">{result.confidence}%</span>
          </div>
          <div className="h-3 bg-muted rounded-full overflow-hidden">
            <div
              className={`h-full rounded-full transition-all duration-1000 ease-out ${progressBarColor}`}
              style={{ width: `${result.confidence}%` }}
            />
          </div>
        </div>
      </div>

      <div className="mt-6 flex flex-col gap-3">
        <Button onClick={generatePDF} className="w-full gap-2" variant="outline">
          <Download className="w-4 h-4" />
          Download Detailed Report
        </Button>

        <p className="text-xs text-center text-muted-foreground">
          Analyzed at {result.timestamp} • For clinical decision support only
        </p>
      </div>
    </div>
  );
};

export default ResultsCard;
